version: '2'

services:
    cassandra_seed:
        image: cassandra:3
        restart: always

    cassandra:
        image: cassandra:3
        restart: always
        environment:
          - CASSANDRA_SEEDS=cassandra_seed

    init:
        image: timmaa/project-bladerunner
        command: ["node", "init.js"]
        environment:
          - CASSANDRA=cassandra_seed

    usecase:
        image: timmaa/project-bladerunner
        restart: always
        environment:
          - SERVICE_NAME=app
          - SERVICE_TAGS=production
          - CASSANDRA=cassandra_seed
          - CONSUL=consul
          - "PUBLISHER=http://nginx_lb:1080/pub"

    nginx_lb:
        image: timmaa/nginx-lb-nchan
        depends_on:
          - usecase
        ports:
          - "80:80"

    consul:
        image: gliderlabs/consul-server:latest
        command: -bootstrap
        
    registrator:
        image: gliderlabs/registrator:master
        depends_on:
          - consul
        command: -internal -resync 600 consul://consul:8500
        volumes:
          - "/var/run/docker.sock:/tmp/docker.sock"
